### ISSUE TITLE
vue3-simple-icons components import seems to break HMR

### ISSUE THREAD

**Issue by dxlliv** [wyatt-herkamp/vue3-simple-icons#1]
It seems they break the Hot Module replacement feature.

I tried to register some globally, but happens also when using them individually.

**Comment by wyatt-herkamp** [comment]
I have not tried the hot module replacement and really don't understand it much

Is this the feature you are talking about

https://vitejs.dev/guide/api-hmr.html

**Comment by dxlliv** [comment]
Yup.

I don't know how it works either,  
but it allows the dev server to reload components once they have been modified.

This feature seems broken when I use `vue3-simple-icons` in my project,  
maybe someone will be able to tell us how to let it work.

For now I disabled icon imports when `import.meta.env.DEV` is true.
Here is my generic `IconBrand` component that loads `vue3-simple-icons` asynchronously.

When dev server is enabled, it loads a Quasar icon instead.
Usage: `<IconBrand name="si-discord" />`

```html
<template>
  <Icon v-if="!devMode"/>
  <q-icon v-else name="mdi-cube"/>
</template>

<script setup>
import {computed, defineAsyncComponent} from 'vue'
import {capitalizeFirstLetter} from "@/utils/utilsString";

const props = defineProps({
  name: String
})

const iconName = computed(() =>
  capitalizeFirstLetter(props.name.substring(3)) + 'Icon'
)

const devMode = import.meta.env.DEV

const Icon = defineAsyncComponent(async () => {
  if (devMode) {
    return false
  }

  const {[iconName.value]: ImportedIcon} = await import('vue3-simple-icons');

  return ImportedIcon
})
</script>

**Comment by wyatt-herkamp** [comment]
Are you using Vite?

**Comment by jaythomas** [comment]
@wyatt-herkamp quasar uses webpack, not vite.

**Comment by jaythomas** [comment]
@dxlliv are you using quasar cli or the vue-cli plugin?

**Comment by jaythomas** [comment]
Using the default configuration with a fresh quasar project, yarn > webpack > vue 3.0.0. I am seeing hot module reload working with adding/swapping out icons and cannot reproduce the issue. My IndexPage.vue:

```vue
<template>
  <q-page class="flex flex-center">
    <div>
      <span>Hi my name is Gerald.</span>
      <ApachemavenIcon style="fill: black" />
      <NpmIcon style="fill: purple" size="24px" />
      <ZigIcon style="fill: black" />
    </div>
    <img
      alt="Quasar logo"
      src="~assets/quasar-logo-vertical.svg"
      style="width: 200px; height: 200px"
    >
  </q-page>
</template>

<script>
import { defineComponent } from 'vue'
import { ApachemavenIcon, NpmIcon, ZigIcon } from 'vue3-simple-icons'

export default defineComponent({
  name: 'IndexPage',
  components: {
    ApachemavenIcon,
    NpmIcon,
    ZigIcon
  }
})
</script>
```

**Comment by dxlliv** [comment]
I was unable to reproduce the issue on a new project too.  
I'll try to investigate a little more, but the problem is apparently not related to `vue3-simple-icons`.

PS: I'm using Quasar with Vite 3.2.1 and Vue 3.2.41

**Comment by dxlliv** [comment]
Cool, it does not occur with Vite 4.0.3!
I'm going to close the issue.
