### ISSUE TITLE
simple-icons version bump

### ISSUE THREAD

**Issue by hotmeteor** [wyatt-herkamp/vue3-simple-icons#2]
Hello, the docs say that this package will follow the https://github.com/simple-icons/simple-icons version, but it's on 9.10.0 and this package is on 7.18.0.

Can you bump the dependency version number, or just make it always use the latest simple-icons version?

Thanks!

**Comment by wyatt-herkamp** [comment]
Thx, I am have been busy and kept forgetting. I will get it done today.

**Comment by wyatt-herkamp** [comment]
Closed in 038d1e6

**Comment by hotmeteor** [comment]
Np, thanks for the quick update!
